"""empty message

Revision ID: 349e6aa1749c
Revises: 793986074416
Create Date: 2025-09-18 17:10:29.356930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '349e6aa1749c'
down_revision = '793986074416'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dependent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('relationship', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dependent')
    # ### end Alembic commands ###
