"""empty message

Revision ID: 845138a119a6
Revises: 349e6aa1749c
Create Date: 2025-09-18 17:32:18.501334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '845138a119a6'
down_revision = '349e6aa1749c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('dependent_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=255), nullable=False),
    sa.Column('systolic', sa.Integer(), nullable=True),
    sa.Column('diastolic', sa.Integer(), nullable=True),
    sa.Column('sugar_mg_dl', sa.Numeric(), nullable=True),
    sa.Column('taken_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dependent_id'], ['dependent.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('record')
    # ### end Alembic commands ###
